/* geniewiki.h generated by valac 0.16.1, the Vala compiler, do not modify */


#ifndef __GENIEWIKI_H__
#define __GENIEWIKI_H__

#include <glib.h>
#include <stdlib.h>
#include <string.h>
#include <glib-object.h>
#include <gio/gio.h>

G_BEGIN_DECLS


#define TYPE_REQUEST (request_get_type ())
typedef struct _Request Request;

#define TYPE_RESPONSE (response_get_type ())
typedef struct _Response Response;

#define TYPE_WEB_SERVER (web_server_get_type ())
#define WEB_SERVER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_WEB_SERVER, WebServer))
#define WEB_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_WEB_SERVER, WebServerClass))
#define IS_WEB_SERVER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_WEB_SERVER))
#define IS_WEB_SERVER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_WEB_SERVER))
#define WEB_SERVER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_WEB_SERVER, WebServerClass))

typedef struct _WebServer WebServer;
typedef struct _WebServerClass WebServerClass;
typedef struct _WebServerPrivate WebServerPrivate;

#define TYPE_WIKI_FILE (wiki_file_get_type ())
#define WIKI_FILE(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_WIKI_FILE, WikiFile))
#define WIKI_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_WIKI_FILE, WikiFileClass))
#define IS_WIKI_FILE(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_WIKI_FILE))
#define IS_WIKI_FILE_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_WIKI_FILE))
#define WIKI_FILE_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_WIKI_FILE, WikiFileClass))

typedef struct _WikiFile WikiFile;
typedef struct _WikiFileClass WikiFileClass;
typedef struct _WikiFilePrivate WikiFilePrivate;

#define TYPE_REQUEST_HANDLER (request_handler_get_type ())
#define REQUEST_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_CAST ((obj), TYPE_REQUEST_HANDLER, RequestHandler))
#define REQUEST_HANDLER_CLASS(klass) (G_TYPE_CHECK_CLASS_CAST ((klass), TYPE_REQUEST_HANDLER, RequestHandlerClass))
#define IS_REQUEST_HANDLER(obj) (G_TYPE_CHECK_INSTANCE_TYPE ((obj), TYPE_REQUEST_HANDLER))
#define IS_REQUEST_HANDLER_CLASS(klass) (G_TYPE_CHECK_CLASS_TYPE ((klass), TYPE_REQUEST_HANDLER))
#define REQUEST_HANDLER_GET_CLASS(obj) (G_TYPE_INSTANCE_GET_CLASS ((obj), TYPE_REQUEST_HANDLER, RequestHandlerClass))

typedef struct _RequestHandler RequestHandler;
typedef struct _RequestHandlerClass RequestHandlerClass;
typedef struct _RequestHandlerPrivate RequestHandlerPrivate;

struct _Request {
	gchar* full_request;
	gchar* path;
	gchar* query;
	gchar* object;
	gchar* action;
	gchar* val;
};

struct _Response {
	gchar* status_code;
	gchar* content_type;
	gchar* text;
	gchar* data;
};

struct _WebServer {
	GObject parent_instance;
	WebServerPrivate * priv;
};

struct _WebServerClass {
	GObjectClass parent_class;
};

struct _WikiFile {
	GObject parent_instance;
	WikiFilePrivate * priv;
};

struct _WikiFileClass {
	GObjectClass parent_class;
};

typedef enum  {
	IO_ERROR_FILE_NOT_FOUND,
	IO_ERROR_FILE_NO_READ_PERMISSION,
	IO_ERROR_FILE_IS_LOCKED
} IOError;
#define IO_ERROR io_error_quark ()
struct _RequestHandler {
	GTypeInstance parent_instance;
	volatile int ref_count;
	RequestHandlerPrivate * priv;
};

struct _RequestHandlerClass {
	GTypeClass parent_class;
	void (*finalize) (RequestHandler *self);
};


extern gboolean show_version;
extern gboolean auto_login;
extern gchar* listen;
extern gint port;
extern gchar* home;
extern gboolean restore;
extern gboolean sendmail;
#define VERSION "0.1.0"
#define DEFAULT_PORT 8001
#define DEFAULT_DIR "/tmp/wiki"
#define FaviconDataLen ((guint) 198)
void _vala_main (gchar** args, int args_length1);
GType request_get_type (void) G_GNUC_CONST;
Request* request_dup (const Request* self);
void request_free (Request* self);
void request_copy (const Request* self, Request* dest);
void request_destroy (Request* self);
GType response_get_type (void) G_GNUC_CONST;
Response* response_dup (const Response* self);
void response_free (Response* self);
void response_copy (const Response* self, Response* dest);
void response_destroy (Response* self);
GType web_server_get_type (void) G_GNUC_CONST;
WebServer* web_server_new (guint16 port, const gchar* dir);
WebServer* web_server_construct (GType object_type, guint16 port, const gchar* dir);
void web_server_serve_response (WebServer* self, Response* response, GDataOutputStream* dos);
void web_server_get_request (WebServer* self, const gchar* line, Request* result);
void web_server_run (WebServer* self);
gboolean web_server_connection_handler (WebServer* self, GSocketConnection* connection);
GType wiki_file_get_type (void) G_GNUC_CONST;
WikiFile* wiki_file_new (const gchar* pagename);
WikiFile* wiki_file_construct (GType object_type, const gchar* pagename);
void wiki_file_store_text (WikiFile* self, const gchar* text);
gboolean wiki_file_exists (WikiFile* self);
GQuark io_error_quark (void);
gchar* wiki_file_as_html (WikiFile* self, GError** error);
const gchar* wiki_file_get_page (WikiFile* self);
void wiki_file_set_page (WikiFile* self, const gchar* value);
#define STATUS_CODE_FILE_NOT_FOUND "HTTP/1.1 404 Not Found\n"
#define STATUS_CODE_OK "HTTP/1.1 200 OK\n"
#define STATUS_CODE_ERROR "HTTP/1.1 500 Internal Server Error\n"
gpointer request_handler_ref (gpointer instance);
void request_handler_unref (gpointer instance);
GParamSpec* param_spec_request_handler (const gchar* name, const gchar* nick, const gchar* blurb, GType object_type, GParamFlags flags);
void value_set_request_handler (GValue* value, gpointer v_object);
void value_take_request_handler (GValue* value, gpointer v_object);
gpointer value_get_request_handler (const GValue* value);
GType request_handler_get_type (void) G_GNUC_CONST;
RequestHandler* request_handler_new (Request* req);
RequestHandler* request_handler_construct (GType object_type, Request* req);
void request_handler_get_response (RequestHandler* self, Response* result);
void request_handler_get_req (RequestHandler* self, Request* result);
void request_handler_set_req (RequestHandler* self, Request* value);
#define WIKI_TEXT_WIKIHEADER "\n" \
"<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Transitional//EN\" \"htt" \
"p://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd\">\n" \
"<!-- WIKIEHEADER -->\n" \
"<html xmlns=\"http://www.w3.org/1999/xhtml\"> \n" \
"<head> \n" \
"<meta http-equiv=\"Content-Type\" content=\"text/html; charset=utf-8\"" \
" /> \n" \
"<link rel=\"SHORTCUT ICON\" href=\"favicon.ico\" /> \n" \
"<link media=\"all\" href=\"styles.css\" rel=\"STYLESHEET\" type=\"text" \
"/css\" /> \n" \
"<title>%s</title> \n" \
"</head> \n" \
"<body>\n"
#define WIKI_TEXT_WIKIFOOTER "</body></html>"
#define WIKI_TEXT_EDITHEADER "\n" \
"<!-- EDITHEADER -->\n" \
"<div id=\"header\">\n" \
"<form method=\"get\" action=\"Search\"> \n" \
"<table border=\"0\" width=\"100%%\"> \n" \
"<tr> \n" \
"<td align=\"left\" ><strong>%s</strong> \n" \
" ( <a href=%s?edit title=\"Edit this wiki page contents. [alt-j]\" acc" \
"esskey=\"j\">Edit</a> |  \n" \
"<a href=%s?delete title=\"Delete page. [alt-d]\" accesskey=\"d\">Delet" \
"e</a> ) </td> \n" \
"<td align=\"right\" > \n" \
"<a href=\"Login\" title=\"Login page. [alt-l]\" accesskey=\"l\">%s</a>" \
" | \n" \
"<a href=\"WikiHome\" title=\"Visit Wiki home page. [alt-z]\" accesskey" \
"=\"z\">Home</a> | \n" \
"<a href=\"Index\" title=\"List all pages in the wiki. [alt-i]\" access" \
"key=\"i\" >Index</a> | \n" \
"<a href=\"Changes\" title=\"List recent changes in the wiki. [alt-r]\"" \
" accesskey=\"r\" >Changes</a> | \n" \
"<a href=\"Create\" title=\"Create a new wiki page by title. [alt-c]\" " \
"accesskey=\"c\">New</a> | \n" \
"<a href=\"WikiHelp\" title=\"Get help on wiki usage and formatting.\">" \
"Help</a>  \n" \
"<input type=\"text\" name=\"expr\" size=\"15\" title=\"Enter text to s" \
"earch for and press return.\" /> </td> \n" \
"</tr> \n" \
"</table> \n" \
"</form> \n" \
"</div> \n" \
"<div id=\"wikidata\">\n"
#define WIKI_TEXT_PAGEHEADER "\n" \
"<!-- PAGEHEADER -->\n" \
"<div id=\"header\"> \n" \
"<form method=\"get\" action=\"Search\"> \n" \
"<table border=\"0\" width=\"100%%\"> \n" \
"<tr> \n" \
"<td align=\"left\" ><strong>%s</strong> %s</td> \n" \
"<td align=\"right\" > \n" \
"<a href=\"WikiHome\" title=\"Visit Wiki home page. [alt-z]\" accesskey" \
"=\"z\">Home</a> | \n" \
"<a href=\"Index\" title=\"List all pages in the wiki. [alt-i]\" access" \
"key=\"i\" >Index</a> | \n" \
"<a href=\"Changes\" title=\"List recent changes in the wiki. [alt-r]\"" \
" accesskey=\"r\" >Changes</a> | \n" \
"<a href=\"Create\" title=\"Create a new wiki page by title. [alt-c]\" " \
"accesskey=\"c\">New</a> |  \n" \
"<a href=\"WikiHelp\" title=\"Get help on wiki usage and formatting.\">" \
"Help</a>  \n" \
"<input type=\"text\" name=\"expr\" size=\"15\" title=\"Enter text to s" \
"earch for and press return.\" /> </td> \n" \
"</tr> \n" \
"</table> \n" \
"</form> \n" \
"</div> \n" \
"<div id=\"wikidata\"> \n"
#define WIKI_TEXT_PAGEFOOTER "\n" \
"<!-- PAGEFOOTER -->\n" \
"</div><div id=\"footer\">CiWiki alias DidiWiki, Version:  %s</div>\n"
#define WIKI_TEXT_SHORTHELP "\n" \
"<!-- SHORTHELP -->\n" \
"<div id=\"header\"> \n" \
"<table border=\"0\" width=\"100%%\"> \n" \
"<tr> \n" \
"<td align=\"left\" > =H1 ==H2 ===H3 | bold | /italic/ | _underscore_ |" \
" -strikethrough- | highlight | \"quote | \n" \
"[link] | * list | ** sublist | # ordered | ---- | {{toc}} | {{private}" \
"}</td> \n" \
"</tr> \n" \
"</table> \n" \
"</div> \n" \
"<div id=\"wikidata\"> \n"
#define WIKI_TEXT_LOGINFORM "\n" \
"<!-- LOGINFORM -->\n" \
"<h1>Login</h1> \n" \
"<p><a href=\"NewAccount\">New user? Please create a new account.</a></" \
"p> \n" \
"<form method=POST action=\"Login\"> \n" \
"<table border=\"0\" width=\"100%%\"> \n" \
"<tr> \n" \
"<td align=\"right\">User name:</td> \n" \
"<td align=\"left\"><input type=\"text\" name=\"username\" /></td> \n" \
"</tr><tr> \n" \
"<td align=\"right\">Password:</td> \n" \
"<td align=\"left\"><input type=\"password\" name=\"password\" /></td> " \
"\n" \
"</tr><tr> \n" \
"<td></td><td align=\"left\"><input type=\"submit\" value=\"Login\" /><" \
"/td> \n" \
"</tr></table> \n" \
"</form> \n"
#define WIKI_TEXT_NEWLOGINFORM "\n" \
"<!-- NEWLOGINFORM -->\n" \
"<h1>Create a new Account</h1> \n" \
"<p>Please choose your user name, your password and enter a valid email" \
" address.<br> \n" \
"You will receive your validation code on your email</p> \n" \
"<form method=POST action=\"Login\"> \n" \
"<table border=\"0\" width=\"100%%\"> \n" \
"<tr> \n" \
"<td align=\"right\">User name:</td> \n" \
"<td align=\"left\"><input type=\"text\" name=\"username\" /></td> \n" \
"</tr><tr> \n" \
"<td align=\"right\">Password:</td> \n" \
"<td align=\"left\"><input type=\"password\" name=\"password\" /></td> " \
"\n" \
"</tr><tr> \n" \
"<td align=\"right\">Your Email:</td> \n" \
"<td align=\"left\"><input type=\"text\" name=\"email\" /></td> \n" \
"</tr><tr> \n" \
"<td align=\"left\" colspan=2><br>A validation code will be returned by" \
" mail.<br><br></td> \n" \
"</tr><tr> \n" \
"<td align=\"right\">Validation Code:</td> \n" \
"<td align=\"left\"><input type=\"text\" name=\"code\" /></td> \n" \
"</tr><tr> \n" \
"</tr><tr> \n" \
"<td></td><td align=\"left\"><input type=\"submit\" value=\"Process it\"" \
" /></td> \n" \
"</tr></table> \n" \
"<input type=\"hidden\" name=\"newaccount\" value=\"on\" />  \n" \
"</form>\n"
#define WIKI_TEXT_CHGPWDFORM "\n" \
"<!-- GHGPWDFORM -->\n" \
"<form method=POST action=\"Login\"> \n" \
"<table border=\"0\" width=\"100%%\"> \n" \
"<tr> \n" \
"<td align=\"right\">Old password:</td> \n" \
"<td align=\"left\"><input type=\"password\" name=\"password\" /></td> " \
"\n" \
"</tr><tr> \n" \
"<td align=\"right\">New password:</td> \n" \
"<td align=\"left\"><input type=\"password\" name=\"newpassword\" /></t" \
"d> \n" \
"</tr><tr> \n" \
"<td align=\"right\">Reenter your password:</td> \n" \
"<td align=\"left\"><input type=\"password\" name=\"newpasswordbis\" />" \
"</td> \n" \
"</tr><tr> \n" \
"</tr><tr> \n" \
"<td></td><td align=\"left\"><input type=\"submit\" value=\"Login\" /><" \
"/td> \n" \
"</tr></table> \n" \
"</form> \n"
#define WIKI_TEXT_LOGINFO "\n" \
"<!-- LOGINFO -->\n" \
"<h1>Login Information</h1> \n" \
"<form method=POST action=\"Login\"> \n" \
"<table border=\"0\" width=\"100%%\"> \n" \
"<tr> \n" \
"<td align=\"right\">IP Address:</td><td>%s</td> \n" \
"</tr><tr> \n" \
"<td align=\"right\">Login name:</td><td>%s</td> \n" \
"</tr><tr> \n" \
"<td></td><td align=\"left\"><input type=\"submit\" name=\"logoff\" val" \
"ue=\"Log Off\" /></td> \n" \
"</tr><td span=2><br>Change your password:<br></td><tr> \n" \
"<td align=\"right\">Old password:</td> \n" \
"<td align=\"left\"><input type=\"password\" name=\"password\" /></td> " \
"\n" \
"</tr><tr> \n" \
"<td align=\"right\">New password:</td> \n" \
"<td align=\"left\"><input type=\"password\" name=\"newpassword\" /></t" \
"d> \n" \
"</tr><tr> \n" \
"<td align=\"right\">Reenter your password:</td> \n" \
"<td align=\"left\"><input type=\"password\" name=\"newpasswordbis\" />" \
"</td> \n" \
"</tr><tr> \n" \
"<td></td><td align=\"left\"><input type=\"submit\" name=\"chgpwd\" val" \
"ue=\"Change Password\" /></td> \n" \
"</tr><tr> \n" \
"</tr><td span=2><br><a href=\"javascript:javascript:history.go(-1)\">R" \
"eturn to the previous page.</a></td><tr> \n" \
"</tr></table> \n" \
"</form> \n"
#define WIKI_TEXT_CREATEFORM "\n" \
"<!-- CREATEFORM -->\n" \
"<form method=POST action=\"Create\"> \n" \
"<input type=\"text\" name=\"title\" /> \n" \
"<p><input type=\"submit\" value=\"Create\" /></p> \n" \
"</form> \n"
#define WIKI_TEXT_EDITFORM "\n" \
"<!-- EDIT FORM -->\n" \
"<form method=POST action=\"%s?edit\" name=\"editform\"> \n" \
"<textarea name=\"wikitext\" rows=\"20\" cols=\"80\" wrap=\"virtual\">%" \
"s</textarea> \n" \
"<p><input type=\"submit\" name=\"save\" value=\"Save\" title=\"[alt-k]" \
"\" accesskey=\"k\"> \n" \
"<input type=\"submit\" name=\"preview\" value=\"Preview\" title=\"[alt" \
"-p]\" accesskey=\"p\"> \n" \
"<input type=\"submit\" name=\"cancel\" value=\"Cancel\" title=\"[alt-c" \
"]\" accesskey=\"c\"></p> \n" \
"</form> \n" \
"<script language=\"JavaScript\"> \n" \
"<!-- \n" \
"/* Give the textarea focus ...less mouse usage but may annoy people ?*" \
"/  \n" \
"document.editform.wikitext.focus() \n" \
"document.editform.wikitext.scrollTop = document.editform.wikitext.scro" \
"llHeight; \n" \
"//--> \n" \
"</script> \n"
#define WIKI_TEXT_EDITPREVIEW "\n" \
"<!-- EDITPREVIEW -->\n" \
"<div id=header><strong>Preview:</strong></div>\n"
#define WIKI_TEXT_DELETEFORM "\n" \
"<!-- DELETEFORM -->\n" \
"<form method=POST action=\"%s?delete\" name=\"deleteform\"> \n" \
"Are you really sure you want to delete the page <strong>%s</strong>? \n" \
"<p><input type=\"submit\" name=\"confirm\" Value=\"OK\"> \n" \
"<input type=\"submit\" name=\"cancel\" value=\"Cancel\">\n" \
"</form>\n"
#define WIKI_TEXT_HOMETEXT "\n" \
"<!-- HOMETEXT -->\n" \
"[images/ciwiki.png] \n" \
"==Welcome to !CiWiki alias !DidiWiki \n" \
"/!CiWiki / is a fork of /!DidiWiki / with several new features added. " \
"\n" \
"CiWiki is a small and simple [http://en.wikipedia.org/wiki/Wiki WikiWi" \
"kiWeb] implementation \n" \
"Ideal for personal note-taking, to do lists, and any other uses you ca" \
"n think of. \n" \
"CiWiki is fast and does not require webserver, database mng and php in" \
"terpreter. \n" \
"For an example of how a !CiWiki entry looks in text form you can [?edi" \
"t edit] this page. Also see WikiHelp for infomation on usage and forma" \
"tting rules. Use The WikiSandbox to experiment. \n" \
"The zipped homepage is here: [files/index.zip] \n" \
"/!CiWiki / is written by [mailto://inphilly@gmail.com Jean-Pierre Redo" \
"nnet] and released under [http://www.gnu.org GNU] [http://www.gnu.org/" \
"copyleft/gpl.html GPL].  \n" \
"Matthew Allum is the original author of /!DidiWiki (2004)\n"
#define WIKI_TEXT_HELPTEXT "\n" \
"=Quick Guide\n" \
"Top toolbar usage\n" \
"* [?edit Edit] Allows you to edit pages ( see below for rules )\n" \
"* [?delete Delete] Allows you to delete pages\n" \
"* [WikiHome Home] Takes you to the wiki front page\n" \
"* [Index Index] List all the pages in the wiki\n" \
"* [Changes Changes] Lists the pages changed by date\n" \
"* [Create New] Creates a new wiki page by title\n" \
"* [WikiHelp Help] Takes you to this help page\n" \
"Use the text entry box to perform a very simple keyword search on the\n" \
"Wiki contents. Hit return to activate the search.\n" \
"Use the WikiSandbox to practice formatting.\n" \
"----\n" \
"=Formatting rules\n" \
"=Top Level Heading\n" \
"  =Top Level Heading (H1)\n" \
"==Second Level Heading\n" \
"  ==Second Level Heading (H2)\n" \
"More levels\n" \
"  === (H3), ==== (H4) etc\n" \
"----\n" \
"The horizontal lines in this page are made with 4 or more dashes:\n" \
" ---- Horizonal line\n" \
"----\n" \
"Paragraphs are separated by an empty line\n" \
"Like this. Another paragraph.\n" \
" Paragraphs are separated by a blank line.\n" \
" Like this. Another paragraph.\n" \
"----\n" \
"*Bold text*, /italic text/, _underscore text_ and -strikethrough-.\n" \
"  *Bold text*, /italic text/, _underscore text_ and -strikethrough-.\n" \
"/*Combination of bold and italics*/\n" \
"  /*Combination of bold and italics*/\n" \
"----\n" \
"{B}Text color{B}\n" \
" {B}Text color{B}\n" \
"(Y)Background color(Y)\n" \
" (Y)Background color(Y)\n" \
"Colors: {B}B blue{B}  {C}C cyan{C}  {G}G green{G}  {P}P pink{P}  {R}R " \
"red{R}  {Y}Y yellow{Y}\n" \
"Colors: (B)B blue(B)  (C)C cyan(C)  (G)G green(G)  (P)P pink(P)  (R)R " \
"red(R)  (Y)Y yellow(Y)\n" \
"----\n" \
"Highlight\n" \
" Highlight\n" \
"-----\n" \
"WikiLinks are formed by two or more words in /camelcase/.\n" \
" WikiLinks are formed by two or more words in /camelcase/.\n" \
"External links begin with http://, like http://www.freepan.org\n" \
" External links begin with http://, like http://www.freepan.org\n" \
"Forced wiki [links] are a alphanumeric string surrounded by square bra" \
"ckets.\n" \
" Forced wiki [links] are a alphanumeric string surrounded by square br" \
"ackets.\n" \
"Named http links have text with an !http:// link inside, like [http://" \
"www.freepan.org FreePAN]\n" \
" Named http links have text with an !http:// link inside, like [http:/" \
"/www.freepan.org FreePAN]\n" \
"Sometimes !WordsShouldNotMakeAWikiLink so put a \"! \" beforehand.\n" \
" Sometimes !WordsShouldNotMakeAWikiLink so put a \"! \" beforehand.\n" \
"Same thing with !http://foobar.com\n" \
" Same thing with !http://foobar.com\n" \
"Open external links in new tags:\n" \
" {{wwwlink=new_tag}} opens external link in a new tag\n" \
" {{wwwlink=current_tag}} opens external link in a current tag\n" \
"----\n" \
"Links to images display the image:\n" \
" Pictures size and border: {{width=100 height=50 border=2}}\n" \
" Return to the default width, height and border: {{picture=default}}\n" \
"{{width=100 height=50 border=1}}\n" \
"http://www.google.com/images/logo.gif\n" \
" http://www.google.com/images/logo.gif\n" \
"Picture http links have picture with an !http:// link inside, like [ht" \
"tp://www.google.com/images/logo.gif http://www.google.com]\n" \
" Picture http links have picture with an !http:// link inside, like [h" \
"ttp://www.google.com/images/logo.gif http://www.google.com]\n" \
"----\n" \
" Video youtube, videomotion, veoh, vimeo, flash... embedded:\n" \
" youtube=http://www.youtube.com/v/---adress--- \n" \
" dailymotion=http://www.dailymotion.com/swf/---adress--- \n" \
" vimeo=http://..... veoh=http://..... flash=http://.....\n" \
" line starts with youtube... and terminate the adress with a space\n" \
"----\n" \
"Unordered lists begin with a \"* \". The number of asterisks determine" \
"s the level:\n" \
"* foo\n" \
"* bar\n" \
"** boom\n" \
"** bam\n" \
"* baz\n" \
"  * foo\n" \
"  * bar\n" \
"  ** boom\n" \
"  ** bam\n" \
"  * baz\n" \
"Ordered lists work the same, but use a \"#\"\n" \
"----\n" \
"Tables begin the line with a \"|\" and before every new column after.\n" \
"| row:1,col:1 | row:1,col:2\n" \
"| row:2,col:1 | row:2,col:2\n" \
" | row:1,col:1 | row:1,col:2\n" \
" | row:2,col:1 | row:2,col:2\n" \
"---\n" \
"Quotation begins with \"\n" \
" \"I had a monumental idea this morning, but I didn't like it\n" \
"\"I had a monumental idea this morning, but I didn't like it\n" \
"----\n" \
"Expand text\n" \
" {{expand}}  or  {{expand=your label here}}\n" \
" text, links, images\n" \
" {{-expand}}\n" \
"{{expand}}\n" \
"text, links: http://www.google.com\n" \
"{{-expand}}\n" \
"Imbricated\n" \
" {{expand}}\n" \
" Some text\n" \
" {{expand}}\n" \
" More text\n" \
" {{-expand}}\n" \
" {{-expand}}\n" \
"{{expand}}\n" \
"Some text\n" \
"{{expand}}\n" \
"More text\n" \
"{{-expand}}\n" \
"{{-expand}}\n" \
"----\n" \
"Collapse text, can be imbricated too.\n" \
" {{collapse}}  or  {{collapse=your label here}}\n" \
" text, links, images\n" \
" {{-collapse}}\n" \
"{{collapse}}\n" \
"text, links: http://www.google.com\n" \
"{{-collapse}}\n" \
"----\n" \
"Install:\n" \
"The file styles.css must be copied in ./didiwiki or in the home direct" \
"ory of didiwiki.\n" \
"----\n" \
"Simple form: ToDo list\n" \
" {{entry}} or {{entry tiny/small/medium/large/huge date}}\n" \
" !{{data}}   (remove ! before this tag)\n" \
" Entries are added in the page after the tag data\n" \
" {{delete}} deletes the selected field\n" \
" {{save}} saves the checked fields\n" \
"{{entry}}\n" \
"{{data}}\n" \
"{{delete}}{{save}}\n" \
"----\n" \
" Table of contents {{toc}} can be between collapse or expand\n" \
"{{collapse=Table of contents}}{{toc}}{{-collapse}}\n" \
"----\n" \
"<Inline> <html> <is> <escaped>.\n" \
"----\n" \
"Lines prefixed with a space are unformatted ( Like examples on this pa" \
"ge )\n" \
"----\n" \
" There is a `keyword` in this line.\n" \
"There is a `keyword` in this line.\n" \
"----\n" \
" Define a private zone in the page with {{private}}\n" \
" Login is required to show after this tag\n" \
"{{private}}\n" \
" This text is hidded if you are not logged!\n" \
"----\n"
#define WIKI_TEXT_STYLESHEET "\n" \
"body { \n" \
"  font-family: Verdana, Arial, Helvetica, sans-serif; \n" \
"  font-size: 90%;   \n" \
"  color: #333333; \n" \
"  margin: 2px; \n" \
"  padding: 2px; \n" \
"} \n" \
"#header { \n" \
"\tfont-size: 90%; \n" \
"\tbackground-color: #eef; \n" \
"\tborder: 1px solid #aaa; \n" \
"\tfont-family: Verdana, Arial, Helvetica, sans-serif; \n" \
"\tpadding: 5px; \n" \
"\tmargin-bottom:20px; \n" \
"} \n" \
"#header input { \n" \
"\tmargin:0px; \n" \
"\tpadding: 0; \n" \
"\tbackground-color: White; \n" \
"\tborder: 1px solid #aaaaaa; \n" \
"\tfont-size: 90%; \n" \
"} \n" \
"#footer { \n" \
"\tfont-size: 10px; \n" \
"\tcolor: #ddd; \n" \
"\tmargin-top:40px; \n" \
"\twidth: 100%; \n" \
"\ttext-align: center; \n" \
"} \n" \
"table.wikitable { background-color: #fff; border: 1px solid #aaa; } \n" \
"table.wikitable td { background-color: #fff; border: 1px solid #aaa; }" \
" \n" \
"pre { \n" \
"\tfont-family: monospace; \n" \
"\tbackground-color: #eee; \n" \
"\tpadding: 2px; \n" \
"\tpadding-left: 10px; \n" \
"\tmargin-left: 20px; \n" \
"\tmargin-right: 20px; \n" \
"} \n" \
"hr { \n" \
" height: 1px; \n" \
" color: #aaaaaa; \n" \
" background-color: #aaaaaa; \n" \
" border: 0; \n" \
" margin: 0.2em 5px 0.2em 5px; \n" \
"} \n" \
"form { \n" \
"\tborder: none; \n" \
"\tmargin: 0; \n" \
"} \n" \
"textarea { \n" \
"\tborder: 1px solid #aaaaaa; \n" \
"\tcolor: Black; \n" \
"\tbackground-color: white; \n" \
"\twidth: 100%; \n" \
"\tpadding: 0.1em; \n" \
"\toverflow: auto; \n" \
"} \n" \
"input { \n" \
"\tmargin-top:1px; \n" \
"\tpadding: 0 0.4em !important; \n" \
"\tbackground-color: White; \n" \
"\tborder: 1px solid #aaaaaa; \n" \
"} \n" \
"a, ulink{ \n" \
"   color: #333; \n" \
"   text-decoration:none; \n" \
"   border-bottom: 1px #333 dotted; \n" \
"   display: inline; \n" \
" } \n" \
"a:hover { \n" \
"   color: #333; \n" \
"   text-decoration: None; \n" \
"   border-bottom: 1px #000 solid; \n" \
"   } \n" \
"a:visited { \n" \
"   color: #333; \n" \
"}\n"

extern const guchar FaviconData[198];
extern const GOptionEntry options[8];

G_END_DECLS

#endif
